name: flutter_test_task_1
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  intl: ^0.18.1 # Added this for localization
  flutter_svg: ^2.0.7
  expandable: ^5.0.1
  flutter_bloc: ^8.1.3
  bloc: any
  meta: any
  equatable: ^2.0.5
  flutter_localizations: # Added this for localization
    sdk: flutter # Added this for localization

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true # Added this for localization
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/close-square.svg
    - assets/icons/emoji-happy.svg
    - assets/icons/tick-square.svg
    - assets/icons/right-arrow.svg
    - assets/icons/plus.svg
    - assets/icons/party-popper.png
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Heavy.ttf
          style: normal
          weight: 900
        - asset: assets/fonts/SF-Pro-Display-HeavyItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/SF-Pro-Display-Light.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/SF-Pro-Display-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/SF-Pro-Display-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-RegularItalic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Semibold.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-SemiboldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Thin.ttf
          style: normal
          weight: 100
        - asset: assets/fonts/SF-Pro-Display-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/SF-Pro-Display-Ultralight.ttf
          style: normal
          weight: 200
        - asset: assets/fonts/SF-Pro-Display-UltralightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/SF-Pro-Display-Black.ttf
          style: normal
          weight: 900
        - asset: assets/fonts/SF-Pro-Display-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-BoldItalic.ttf
          style: italic
          weight: 700

    - family: SFProText
      fonts:
        - asset: assets/fonts/sf-pro-text-bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/SF-Pro-Text-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/sf-pro-text-heavy.ttf
          style: normal
          weight: 800
        - asset: assets/fonts/SF-Pro-Text-HeavyItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/sf-pro-text-light.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/SF-Pro-Text-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/sf-pro-text-medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/sf-pro-text-regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-RegularItalic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/sf-pro-text-semibold.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/SF-Pro-Text-SemiboldItalic.ttf
          style: italic
          weight: 600